# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rafael Peñaloza Nyssen
email: rafael.penaloza@unimib.it
author: Rafael Peñaloza
description: > # this means to ignore newlines until "baseurl:"
  Academic webpage of Rafael Peñaloza at the University of Milano-Bicocca.
  Information about publications, teaching, and events.
baseurl: "" # the subpath 
url: "http://rpenalozan.github.io" # the base hostname & protocol 

# Build settings
markdown: kramdown
theme: minima
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include: 
  - '_pages'
  - '_data'
defaults:
  - scope:
      path: "papers"
    values:
      paper: true
